"""Shared rubric, output schema, and row-handling for the three AI-usage judges.

All three detectors (GPT, Gemini, Claude) import from here so an "80" means the
same thing to each model: identical criteria, identical 0-100 bands, identical
output contract. Only the per-SDK call mechanics differ in each detector file.
"""
import time

import pandas as pd
from dotenv import load_dotenv
from pydantic import BaseModel, Field

# Load .env once for every detector (the original demos never did this themselves).
load_dotenv()

# Exclusion is decided by consensus.py, not here, but the constants live with the
# rubric so the rubric and the threshold it targets stay in sync.
THRESHOLD = 80          # a judge "flags" a prompt when its score is >= THRESHOLD
MIN_AGREEMENT = 2       # exclude a prompt when at least this many of 3 judges flag it

# (input, output) USD per 1,000,000 tokens, keyed by model id. The Claude rate is
# Anthropic's published pricing for claude-haiku-4-5. The GPT/Gemini rates are left
# as None on purpose: token counts below are always exact, but dollar figures only
# appear once you fill in a verified rate for that provider.
PRICES: dict[str, tuple[float | None, float | None]] = {
    "claude-haiku-4-5": (1.00, 5.00),
    "gpt-5.4-mini": (0.75, 4.50),       # current OpenAI pricing
    "gpt-5.4-nano": (0.20, 1.25),       # TODO: set from current OpenAI pricing
    "gemini-2.5-flash": (0.30, 2.50),   # TODO: set from current Gemini pricing
}


class UsageAccumulator:
    """Running total of token usage for one judge, summed over real API calls.

    Only updated on a cache miss (score_dataframe scores each unique prompt once),
    so the totals reflect actual spend, not the number of trials.
    """

    def __init__(self) -> None:
        self.calls = 0
        self.input_tokens = 0
        self.output_tokens = 0

    def add(self, input_tokens: int, output_tokens: int) -> None:
        self.calls += 1
        self.input_tokens += int(input_tokens or 0)
        self.output_tokens += int(output_tokens or 0)

    def cost_usd(self, model: str) -> float | None:
        rate = PRICES.get(model)
        if not rate or rate[0] is None or rate[1] is None:
            return None
        return self.input_tokens / 1e6 * rate[0] + self.output_tokens / 1e6 * rate[1]


def print_usage_report(accumulators: dict[str, UsageAccumulator]) -> None:
    """Print per-model token usage and (where a rate is known) estimated cost."""
    print("\n=== AI-usage judge spend ===")
    total = 0.0
    any_unknown = False
    for model, acc in accumulators.items():
        cost = acc.cost_usd(model)
        if cost is None:
            any_unknown = True
            cost_str = "cost n/a (set PRICES)"
        else:
            total += cost
            cost_str = f"${cost:.4f}"
        print(f"  {model:<20} calls={acc.calls:<4} "
              f"in={acc.input_tokens:<8} out={acc.output_tokens:<7} {cost_str}")
    known = f"${total:.4f}" + (" (excludes models with no rate set)" if any_unknown else "")
    print(f"  {'TOTAL (priced)':<20} {known}")

USER_TEMPLATE = "Image prompt:\n{prompt}"

# Shared rubric. The 80-100 band keys on writing REGISTER, not amount of detail: a judge
# reaches it when the overall register clearly points to an AI chatbot (polished essayistic
# prose, elevated vocabulary, generation jargon, or boilerplate), because in this task the
# expected genuine-human output (long, detailed, object-by-object and spatial, sometimes
# opening with "photo realistic") superficially resembles an image-generation prompt. The
# discriminator is register + plain human vocabulary, not amount of detail, object count, or
# fragment/tag style. The signal lists are weighted cues, not hard rules — any of them can
# occasionally appear on the other side.
SYSTEM_PROMPT = """
You are a linguistic-forensics assistant for a psychology experiment.

In this experiment, human participants were asked to describe a target image in as much detail as possible so that an AI image generator could recreate it. Because of this, a typical genuine response is expected to be long and detailed, to catalogue many objects with their colors, positions, and spatial layout (foreground/background, left/right, what is cut off by the frame), and it may open with phrasing like "photo realistic" (some participants use such phrasing, many do not). What usually characterizes a real person doing this task is that all of this descriptive, spatial detail is expressed in plain, everyday, human-like words.

Your job is to estimate how strongly the text looks like it was generated by an AI chatbot or language model (for example, copied from ChatGPT) rather than written by the participant themselves. Return a suspicion_score from 0 to 100. Judge mainly the writing STYLE and REGISTER, not the amount of detail, the number of objects, or the presence of spatial/framing description — those are expected from everyone and are not, on their own, evidence of AI. Simple, unpolished, or non-native English is likewise not evidence of AI; do not raise the score merely because the writing seems unsophisticated or non-native. (Genuinely polished, essayistic writing can still be a cue — but judge that from the register signals below, not from assumptions about the writer.)

Signals that may RAISE suspicion (toward AI / chatbot text). Weigh them together and in context; none is decisive on its own, and any of them can occasionally appear in genuine human writing:
- Chatbot framing or boilerplate: an introduction or sign-off, "Sure, here's...", "Certainly", section headings, or markdown-style bullet or numbered lists.
- A polished, essayistic register sustained across the whole text: flowing, well-formed sentences with elevated or marketing-style vocabulary that goes beyond plainly naming what is in the image.
- Uniformly flawless spelling, grammar, spacing, and capitalization across a long passage, together with a complete absence of typos, hedging, or self-correction.
- Explicit image-generation parameters a person describing a photo would be unlikely to type: "8k", "hyper-detailed", "cinematic lighting", "octane render", "bokeh", "35mm", "masterpiece", "trending on artstation", "--ar 16:9", "negative prompt".

Signals that point toward a genuine human doing the task (these LOWER suspicion):
- Plain, everyday vocabulary and simple phrasing, including casual counting and naming ("3 chairs", "1 child", "a potted plant").
- Object-by-object spatial description of the scene ("on the left", "in the foreground", "goes off screen", "behind the table"), whether written as full sentences or as comma-separated fragments.
- Hedging, uncertainty, or self-correction ("almost looks like", "I think", "maybe", "not sure", "it seems").
- Mechanical imperfections: typos, doubled or missing words, doubled spaces, inconsistent capitalization, run-on sentences.
- Conversational or informal asides.

Scoring bands:
0-30: reads like a person describing the image in their own words — plain vocabulary and spatial/object detail, possibly with hedging or imperfections.
31-60: mostly human, with some polished or generic touches but nothing that clearly points to a chatbot.
61-79: mixed — some real pull toward chatbot register alongside human-looking cues, without a clear overall verdict.
80-100: the writing register, on the whole, points clearly to an AI chatbot rather than a person typing — for example a polished, essayistic style with elevated or marketing vocabulary sustained across the text, explicit image-generation parameters or jargon, or chatbot framing/boilerplate — with little sign of a real person typing (plain words, hedging, self-correction, or mechanical slips). You need not be certain the text is entirely AI; assign this band whenever the overall register clearly points to AI. A long, detailed, or fragmented description written in plain everyday words does not, by itself, belong here.

Return only the requested structured fields. The explanation must be one concise sentence naming the specific textual cues behind the score.
""".strip()


class PromptSuspicionResult(BaseModel):
    suspicion_score: int = Field(
        ge=0, le=100, description="Suspicion score from 0 to 100."
    )
    explanation: str = Field(
        description="One concise sentence explaining the observable textual basis for the score."
    )


def _clean_prompt(prompt) -> str:
    return "" if pd.isna(prompt) else str(prompt)


def retry(score_one, prompt: str, max_retries: int = 3) -> PromptSuspicionResult:
    """Call a single-prompt scorer with exponential backoff."""
    last_error = None
    for attempt in range(max_retries):
        try:
            return score_one(prompt)
        except Exception as exc:  # noqa: BLE001 - surfaced after retries
            last_error = exc
            if attempt < max_retries - 1:
                time.sleep(2 ** attempt)
    raise RuntimeError(f"Failed to score prompt after {max_retries} attempts: {last_error}")


def score_dataframe(
    df: pd.DataFrame,
    score_one,
    score_col: str = "suspicion_score",
    expl_col: str = "explanation",
    limit: int | None = None,
) -> pd.DataFrame:
    """Score the 'prompt' column of df, inserting score_col/expl_col right after it.

    - Empty/NaN prompts are skipped (score 0).
    - Identical prompt strings are scored once and reused (dedup cache) to save API calls.
    - Per-row exceptions are caught and recorded as pd.NA + an error message.
    - limit: only score the first `limit` rows (rest left as pd.NA) — a cost guard.
    """
    if "prompt" not in df.columns:
        raise ValueError('Input must contain a column named "prompt".')

    df = df.copy()
    scores: list = []
    explanations: list = []
    cache: dict[str, PromptSuspicionResult] = {}

    for idx, raw in enumerate(df["prompt"]):
        prompt = _clean_prompt(raw)

        if limit is not None and idx >= limit:
            scores.append(pd.NA)
            explanations.append(pd.NA)
            continue

        if not prompt.strip():
            scores.append(0)
            explanations.append("Empty prompt; no textual evidence of AI-style prompting.")
            continue

        try:
            if prompt in cache:
                result = cache[prompt]
            else:
                result = retry(score_one, prompt)
                cache[prompt] = result
            scores.append(result.suspicion_score)
            explanations.append(result.explanation)
        except Exception as exc:  # noqa: BLE001
            scores.append(pd.NA)
            explanations.append(f"Scoring failed: {type(exc).__name__}: {exc}")

        if (idx + 1) % 50 == 0:
            print(f"Scored {idx + 1} rows...")

    for col in (score_col, expl_col):
        if col in df.columns:
            df = df.drop(columns=[col])
    pos = df.columns.get_loc("prompt")
    df.insert(pos + 1, score_col, scores)
    df.insert(pos + 2, expl_col, explanations)
    return df
