name: Use API Key

on:
  workflow_dispatch:

jobs:
  just-run:
    runs-on: ubuntu-latest

    env:
      STABILITY_API_KEY: ${{ secrets.STABILITY_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Python script
      run: |
        python api_model.py
